### ISSUE TITLE
Inconsistency Between License in README and package.json

### ISSUE THREAD

**Issue by blue-monk** [Yukaii/quiver-markdown-exporter#1]
The README states that the license is MIT.
However, the 'license' field in the `package.json` is set to 'ISC'.
Is this a mistake, and should it be 'MIT' instead?

**Comment by Yukaii** [comment]
It should be MIT. I forgot to change the license inside package.json. Thanks for the reminder.

**Comment by Yukaii** [comment]
https://github.com/Yukaii/quiver-markdown-exporter/commit/bcc2ee40c884329d2853893307305d84b9e8c2b0

**Comment by blue-monk** [comment]
Thanks for fixing the license info so quickly! I really appreciate it.
